// GENERATED by scripts/sync-api-contracts.mjs from apps/api/src/config/vocab.ts.
// Do not edit by hand: run `pnpm sync:contracts` in packages/sdk.

/*
 * Every closed vocabulary the API serves, one const and one union each. The
 * spec publishes each as a named component and references it wherever the
 * value appears; the hand-written models use these unions so a value the
 * API can send is one a caller can switch on.
 */

/** Production status of a firearm. Closed: these are every value the catalog holds. */
export const FIREARM_STATUSES = [
  'in_production',
  'discontinued',
  'out_of_production',
  'in_service',
  'limited_production',
  'prototype',
] as const

export type FirearmStatus = (typeof FIREARM_STATUSES)[number]

/** In descending order of how often each occurs in the catalog. */
export const FIREARM_ACTION_TYPES = [
  'short_recoil',
  'bolt_action',
  'blowback',
  'break_action',
  'gas_operated',
  'gas_operated_long_stroke',
  'gas_operated_direct_impingement',
  'revolving',
  'gas_operated_short_stroke',
  'muzzleloader',
  'pump_action',
  'lever_action',
  'double_action',
  'falling_block',
  'roller_delayed_blowback',
  'single_action',
  'gas_operated_short_stroke_piston',
  'single_action_revolver',
  'double_action_revolver',
  'inertia_operated',
  'recoil_operated',
  'delayed_blowback',
  'long_recoil',
  'gas_operated_rotating_bolt',
  'breech_loading',
  'rolling_block',
  'straight_pull',
  'trapdoor',
  'spring_piston',
  'hinged_breechblock',
  'lever_delayed_blowback',
  'blow_forward',
  'electric_gatling',
  'double_action_only',
  'rotating_barrel',
  'pneumatic',
  'gas_operated_dual_mode',
  'delayed_blowback_rotating_barrel',
  'gas_delayed_blowback',
  'radial_delayed_blowback',
  'short_recoil_rotating_barrel',
  'gas_operated_balanced_automatics',
  'gas_operated_balanced_recoil',
  'gas_operated_blow_forward',
  'gas_operated_open_bolt',
  'gas_operated_tilting_bolt',
] as const

export type FirearmActionType = (typeof FIREARM_ACTION_TYPES)[number]

/** How the round is set off. */
export const FIREARM_FIRING_MECHANISMS = [
  'striker_fired',
  'hammer_fired',
  'double_action',
  'double_action_only',
  'single_action',
  'double_action_single_action',
  'open_bolt',
  'closed_bolt',
  'rotating_bolt',
  'internal_hammer',
  'fixed_firing_pin',
  'flintlock',
  'matchlock',
  'wheellock',
  'miquelet_lock',
  'percussion',
  'percussion_cap',
  'single_action_only',
  'traditional_double_action',
  'solenoid_fired',
  'externally_powered',
  'hammerless',
  'pneumatic',
] as const

export type FirearmFiringMechanism = (typeof FIREARM_FIRING_MECHANISMS)[number]

/** What the trigger does, as distinct from what sets the round off. */
export const FIREARM_TRIGGER_TYPES = [
  'safe_action',
  'single_stage',
  'single_action',
  'two_stage',
  'double_action',
  'double_action_single_action',
  'da_sa',
  'set_trigger',
  'progressive_two_stage',
  'select_fire',
  'automatic',
  'automatic_only',
  'full_auto_only',
  'semi_auto',
  'flat_faced',
  'single_action_with_restrike',
  'double_trigger',
  'single_trigger',
  'double_action_only',
  'single_action_only',
  'single_selective',
  'selective_fire',
  'double_set',
  'single_set',
  'striker_fired',
  'adjustable',
  'adjustable_single_stage',
  'adjustable_two_stage',
  'adjustable_match',
  'two_stage_adjustable_match',
  'quattro_two_stage_adjustable',
  'match',
  'progressive',
  'electronic',
  'contact_fire',
  'strike_two',
  'flat_face_safe_action',
  'sheathed_trigger',
  'self_defense_trigger',
  'concealed_hammer',
  'internal_hammer',
  'ring_trigger',
  'spade_grip',
  'thumb_triggers',
] as const

export type FirearmTriggerType = (typeof FIREARM_TRIGGER_TYPES)[number]

/** How rounds are held and fed. */
export const FIREARM_MAGAZINE_TYPES = [
  'detachable_box',
  'detachable_single_stack_box',
  'fixed_box',
  'internal',
  'drum',
  'belt',
  'belt_fed',
  'disintegrating_link_belt',
  'tube',
  'tubular',
  'dual_tubular',
  'rotary',
  'revolving_cylinder',
  'helical',
  'en_bloc_clip',
  'stripper_clip',
  'internal_box',
  'integral',
  'feed_strip',
  'pan',
  'detachable_triple_box',
  'single_shot',
  'none',
] as const

export type FirearmMagazineType = (typeof FIREARM_MAGAZINE_TYPES)[number]

/** Production status of an attachment. `limited` corresponds to a firearm's `limited_production`. */
export const ATTACHMENT_STATUSES = [
  'in_production',
  'discontinued',
  'limited',
] as const

export type AttachmentStatus = (typeof ATTACHMENT_STATUSES)[number]

/** What kind of asset a media row is. */
export const MEDIA_KINDS = [
  'silhouette',
  'render',
  'photo',
  'schematic',
  'model',
] as const

export type MediaKind = (typeof MEDIA_KINDS)[number]

/** The storage label on `FirearmImage.type`, predating `kind`: `svg` is `silhouette`, `3d_model` is `model`, and `gallery` is the default an upload lands on. Branch on `kind`. */
export const IMAGE_TYPES = [
  'svg',
  'photo',
  '3d_model',
  'gallery',
  'primary',
  'thumbnail',
  'render',
  'profile',
  'angle',
  'detail',
] as const

export type ImageType = (typeof IMAGE_TYPES)[number]

/** What a schematic document is. */
export const SCHEMATIC_TYPES = [
  'blueprint',
  'spec_sheet',
  'manual',
  'datasheet',
  'exploded_view',
  'reference',
] as const

export type SchematicType = (typeof SCHEMATIC_TYPES)[number]

/** Lifecycle of a support ticket. `waiting` means we are waiting on the customer. */
export const TICKET_STATUSES = [
  'open',
  'in_progress',
  'waiting',
  'resolved',
  'closed',
] as const

export type TicketStatus = (typeof TICKET_STATUSES)[number]

/** Support ticket priority. */
export const TICKET_PRIORITIES = [
  'low',
  'normal',
  'high',
  'urgent',
] as const

export type TicketPriority = (typeof TICKET_PRIORITIES)[number]

/** What a support ticket is about. */
export const TICKET_CATEGORIES = [
  'billing',
  'technical',
  'data_quality',
  'feature_request',
  'other',
] as const

export type TicketCategory = (typeof TICKET_CATEGORIES)[number]

/** What a data report says is wrong. */
export const REPORT_ISSUE_TYPES = [
  'incorrect',
  'missing',
  'outdated',
] as const

export type ReportIssueType = (typeof REPORT_ISSUE_TYPES)[number]

/** Lifecycle of a data report. */
export const REPORT_STATUSES = [
  'pending',
  'reviewed',
  'resolved',
  'dismissed',
] as const

export type ReportStatus = (typeof REPORT_STATUSES)[number]

/** What a site update is about: the catalogue, the platform, a policy, the company, or an incident. */
export const UPDATE_KINDS = [
  'catalog',
  'platform',
  'policy',
  'company',
  'incident',
] as const

export type UpdateKind = (typeof UPDATE_KINDS)[number]

/** The kind of block in a site update body. Each maps to a renderer on the website. */
export const UPDATE_BLOCK_TYPES = [
  'paragraph',
  'heading',
  'list',
  'quote',
  'code',
  'figure',
] as const

export type UpdateBlockType = (typeof UPDATE_BLOCK_TYPES)[number]

/** A character-field pattern an update may name in place of a photograph. The website draws it. */
export const UPDATE_GLYPH_PATTERNS = [
  'impact',
  'ballistics',
  'rounds',
  'sweep',
  'waves',
  'thread',
  'lattice',
  'words',
] as const

export type UpdateGlyphPattern = (typeof UPDATE_GLYPH_PATTERNS)[number]

/** Where an interface row on a firearm came from. `curated` is a person; `inferred` is the backfill, capped at 0.6 confidence; the inherited kinds came through the parent chain or a platform. */
export const INTERFACE_SOURCES = [
  'curated',
  'inferred',
  'inherited:parent',
  'inherited:platform',
] as const

export type InterfaceSource = (typeof INTERFACE_SOURCES)[number]

/** How a fit was reached: on the firearm's own interface, through one adapter, or by a curated override. */
export const FIT_TYPES = [
  'direct',
  'adapter',
  'curated',
] as const

export type FitType = (typeof FIT_TYPES)[number]

/** The weakest evidence behind a fit. A retailer or engineering consumer should treat `inferred` as unverified; `min_confidence` hides it. */
export const FIT_SOURCES = [
  'curated',
  'universal',
  'inferred',
  'inherited:parent',
  'inherited:platform',
] as const

export type FitSource = (typeof FIT_SOURCES)[number]

/** What kind of page a cited source is, strongest first: the maker's own page, a standards body (SAAMI, C.I.P.), a government or military document, an independent reference work, a specification aggregator, the press, a retailer or auction listing, a community site, or an unclassified page. Weigh a figure by the best kind behind it, never by how many pages were cited. */
export const SOURCE_KINDS = [
  'manufacturer',
  'standards_body',
  'government',
  'reference',
  'aggregator',
  'press',
  'retailer',
  'community',
  'other',
] as const

export type SourceKind = (typeof SOURCE_KINDS)[number]

/** The role a firearm's game profile assigns it. */
export const GAME_ARCHETYPES = [
  'sniper',
  'assault',
  'tank',
  'glass-cannon',
  'all-rounder',
  'support',
  'stealth',
  'speedster',
] as const

export type GameArchetype = (typeof GAME_ARCHETYPES)[number]

/** What kind of change a changelog entry records. */
export const CHANGELOG_CATEGORIES = [
  'feature',
  'improvement',
  'bugfix',
  'data',
  'breaking',
] as const

export type ChangelogCategory = (typeof CHANGELOG_CATEGORIES)[number]

/** How prominently a site notice is shown. */
export const NOTICE_VARIANTS = [
  'info',
  'warning',
  'critical',
] as const

export type NoticeVariant = (typeof NOTICE_VARIANTS)[number]

/** Whether a seller listing is public. */
export const OFFER_STATUSES = [
  'draft',
  'published',
] as const

export type OfferStatus = (typeof OFFER_STATUSES)[number]

/** What a seller listing is for. */
export const OFFER_TARGET_KINDS = [
  'attachment',
  'firearm',
] as const

export type OfferTargetKind = (typeof OFFER_TARGET_KINDS)[number]

/** The kind of body that adopted a firearm. */
export const ADOPTION_TYPES = [
  'military',
  'law_enforcement',
  'civilian',
  'paramilitary',
  'special_forces',
  'private_security',
  'training',
  'commercial',
  'government',
  'sporting',
  'tribal',
  'insurgent',
  'intelligence',
] as const

export type AdoptionType = (typeof ADOPTION_TYPES)[number]
