// GENERATED by scripts/sync-api-contracts.mjs from apps/api/src/schemas/webhooks.ts.
// Do not edit by hand: run `pnpm sync:contracts` in packages/sdk.

/** Every event a webhook endpoint may subscribe to. */
export const WEBHOOK_EVENT_TYPES = [
  'firearm.created',
  'firearm.updated',
  'firearm.deleted',
  'firearm.variant.updated',
  'firearm.source.changed',
  'firearm.confidence.changed',
  'manufacturer.created',
  'manufacturer.updated',
  'manufacturer.deleted',
  'caliber.created',
  'caliber.updated',
  'caliber.deleted',
  'category.created',
  'category.updated',
  'category.deleted',
  'image.created',
  'image.deleted',
  'catalog.resynced',
] as const

export type WebhookEventType = (typeof WEBHOOK_EVENT_TYPES)[number]

/** Type guard for a string the SDK recognises as an event type. */
export function isWebhookEventType(value: unknown): value is WebhookEventType {
  return typeof value === 'string' && (WEBHOOK_EVENT_TYPES as readonly string[]).includes(value)
}
